#!/bin/sh

DATE=$(date "+%Y-%m-%d-%H-%S-%M")
OUT_FILE="${BACKUP_PATH}/${DATE}.gz"

# Remove old backups
find ${BACKUP_PATH} -mtime +${BACKUP_LEFETIME} -type f -delete

mongodump --uri ${MONGO_URL} --gzip --archive=${OUT_FILE}
